name: 🖌 SDK Feature Request
description: Propose a feature or improvement that the Storyblok SDK should have
labels: [enhancement, pending-triage, pending-author]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve the Storyblok open source project, you rock!
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: 'Clear and concise description of what you want to include or enhance from the SDK. Please make the reason and usecases as detailed as possible. If you intend to submit a PR for this feature request, tell us in the description so we can review and be aware of it. Thanks in advance!'
      placeholder: As a developer using Storyblok SDK I want [wish] so that [benefit].
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution or improvement
      description: Link to the PR or what implementation you will expect from us (links to external examples if needed).
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the feature request, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://a.storyblok.com/f/88751/x/ef38c36cf3/storyblok-code-of-conduct_v2.pdf?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)
          required: true
  - type: markdown
    attributes:
      value: |
        > This template was inspired by the [Vite FR template](https://github.com/vitejs/vite/blob/main/.github/ISSUE_TEMPLATE/feature_request.yml)
